name:                hack-assembler
version:             0.1.0.0
github:              "AlexanderCecile/hack-assembler"
license:             BSD3
author:              "Alexander Cécile"
maintainer:          "alexander.m.cecile@gmail.com"
copyright:           "2020 Alexander Cécile"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/AlexanderCecile/hack-assembler#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  hack-assembler-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hack-assembler

tests:
  hack-assembler-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hack-assembler
